import type { Product } from "@/types/content";
import { ProductGridCard } from "@/components/reference/category/ProductGridCard";

const SERUM_PRODUCTS: Product[] = [
  {
    id: "vinoperfect-duo",
    badge: "Limited edition",
    title: "Vinoperfect",
    subtitle: "Dark Spot Brightening Serum & SPF50+ Cream Duo",
    image: "/images/reference/category/vinoperfect-duo.jpg",
    rating: 4.7,
    reviewCount: 1562,
    price: 53.0,
    href: "#",
  },
  {
    id: "vinoperfect-jumbo",
    badge: "Special offer",
    title: "Vinoperfect",
    subtitle: "Dark Spot Brightening Serum Vitamin C Alternative - Jumbo",
    image: "/images/reference/category/vinoperfect-jumbo.jpg",
    rating: 4.8,
    reviewCount: 5257,
    price: 74.0,
    href: "#",
  },
  {
    id: "vinoperfect-30ml",
    badge: "Bestseller",
    title: "Vinoperfect",
    subtitle: "Dark Spot Brightening Serum Vitamin C Alternative - 30ml",
    image: "/images/reference/category/vinoperfect-30ml.jpg",
    rating: 4.8,
    reviewCount: 5257,
    price: 53.0,
    href: "#",
  },
  {
    id: "vinoperfect-routine",
    badge: "Bestseller",
    title: "Vinoperfect",
    subtitle: "Radiance and Anti-dark spot Routine",
    image: "/images/reference/category/vinoperfect-routine.jpg",
    rating: 4.7,
    reviewCount: 786,
    price: 137.0,
    href: "#",
  },
  {
    id: "vinopure-serum",
    badge: "New",
    title: "Vinopure",
    subtitle: "Blemish Control Salicylic Serum",
    image: "/images/reference/category/vinopure-serum.jpg",
    rating: 4.6,
    reviewCount: 1759,
    price: 34.0,
    href: "#",
  },
  {
    id: "resveratrol-lift-serum",
    badge: "Bestseller",
    title: "Resveratrol-Lift",
    subtitle: "Instant Firming Retinol Alternative Serum",
    image: "/images/reference/category/resveratrol-lift-serum.jpg",
    rating: 4.7,
    reviewCount: 2188,
    price: 54.0,
    href: "#",
  },
  {
    id: "resveratrol-lift-refill",
    badge: "New",
    title: "Resveratrol-Lift",
    subtitle: "Instant Firming Serum - Refill",
    image: "/images/reference/category/resveratrol-lift-refill.jpg",
    rating: 4.7,
    reviewCount: 1260,
    price: 46.0,
    href: "#",
  },
  {
    id: "premier-cru-serum",
    badge: "New",
    title: "Premier Cru",
    subtitle: "The Serum",
    image: "/images/reference/category/premier-cru-serum.jpg",
    rating: 4.8,
    reviewCount: 566,
    price: 92.0,
    href: "#",
  },
  {
    id: "vinohydra-serum",
    badge: "Bestseller",
    title: "VinoHydra",
    subtitle: "Hyaluronic Serum",
    image: "/images/reference/category/vinohydra-serum.jpg",
    rating: 4.7,
    reviewCount: 638,
    price: 31.0,
    href: "#",
  },
  {
    id: "vinopure-routine",
    badge: "Limited edition",
    title: "Vinopure",
    subtitle: "Global Anti-blemish Routine",
    image: "/images/reference/category/vinopure-routine.jpg",
    rating: 4.7,
    reviewCount: 2220,
    price: 78.0,
    href: "#",
  },
  {
    id: "resveratrol-lift-duo",
    badge: "New",
    title: "Resveratrol-Lift",
    subtitle: "Instant Firming Serum & Refill Duo",
    image: "/images/reference/category/resveratrol-lift-duo.jpg",
    rating: 4.8,
    reviewCount: 1207,
    price: 100.0,
    href: "#",
  },
  {
    id: "premier-cru-routine",
    badge: "New",
    title: "Premier Cru",
    subtitle: "Global Anti-Ageing Routine",
    image: "/images/reference/category/premier-cru-routine.jpg",
    rating: 4.8,
    reviewCount: 2371,
    price: 233.0,
    href: "#",
  },
];

export function ProductGrid() {
  return (
    <div className="grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3 lg:grid-cols-4">
      {SERUM_PRODUCTS.map((product) => (
        <ProductGridCard key={product.id} product={product} />
      ))}
    </div>
  );
}
